import os

PREMIUM_PICKS_CHANNEL_ID = os.getenv('PREMIUM_PICKS_CHANNEL_ID')
FREE_DAILY_PICKS_CHANNEL_ID = os.getenv('FREE_DAILY_PICKS_CHANNEL_ID')
DAILY_STATS_CHANNEL_ID = os.getenv('DAILY_STATS_CHANNEL_ID')
WEEKLY_STATS_CHANNEL_ID = os.getenv('WEEKLY_STATS_CHANNEL_ID')
MONTHLY_STATS_CHANNEL_ID = os.getenv('MONTHLY_STATS_CHANNEL_ID')


VALID_CHANNELS = {
    PREMIUM_PICKS_CHANNEL_ID,
    DAILY_STATS_CHANNEL_ID,
    WEEKLY_STATS_CHANNEL_ID,
    MONTHLY_STATS_CHANNEL_ID,
}

INTERVAL_TO_CHANNEL_ID = {
    "D": DAILY_STATS_CHANNEL_ID,
    "W": WEEKLY_STATS_CHANNEL_ID,
    "M": MONTHLY_STATS_CHANNEL_ID,
}

HRS = 22
MINS = 47